### ISSUE TITLE
Timer abuse

### ISSUE THREAD

**Issue by 4everGhost** [jonitaikaponi/ckSurf#25]
Hey jonitaikaponi,

there is a new method to abuse the surf timer on maps with stages. I had to delete three map records in two days, so it is getting exploited at the moment. This is exploit is not only working on my server but also on others.

Because of that I will send you a private message in the alliedmods forum under my nickname "Gh2t" with the detailed instructions to reproduce this bug.

I hope you can fix it.

PS.: I love your plugin

**Comment by jonitaikaponi** [comment]
Pushed a temp fix for this. It is not tested yet.

**Comment by nikooo777** [comment]
there are still several ways of exploiting this.
Players are somehow teleporting to the end of the map and setting absurd time records.
I went through the source code a little, however without any comments it's hard to figure out exactly what and why you're doing some stuff.

What i guess is that you don't have a proper way of stopping the timer when players use dangerous actions such as teleporting. I see that you implemented a Client_stop but only use it in a couple of methods. Perhaps you should use that in every *dangerous* callback, also I don't understand why you need timers such as:
CreateTimer(0.4, timerAfterTele, client);
What's the point? and why 0.4 seconds?

I might not be right here, but it appears that in some cases you're stopping the timer inside those weird timer callbacks, this opens a wide world of abusing with this *small* timeframe the timer takes to execute. 

Please consider patching this as soon as possible as this is getting more and more abused.

Greetings and thanks for your work

**Comment by marcowmadeira** [comment]
You are right, players have still 0.4 seconds to finish the map before the timer stops. The whole code needs to be redone, there are a lot of code that aren't being used.

**Comment by jonitaikaponi** [comment]
Hey,

The reason for the Client_Stop and the timer are to fix different exploits.

What happens when a player teleports from within the start zone to another location is that the teleport happens and then the zone gets triggered on the player. So if a player teleports from within the zone, the trigger to start the players timer happens after the teleportation, hence the timer. The 0.4 seconds is just so that even the slowest servers can handle the teleportation and the trigger first. This definately isn't the the best solution by any means, and was done just to fix this issue simply and quickly, as I was focusing on the new ckSurf version.

The other exploit is when a player teleports just when leaving the zone. What happens here is that the player leaves the start zone -> his timer starts, but at the same time he teleports and his timer doesn't get stopped, because of syncing issues. Client_Stop has been able to fix these issues.

I just realeased the beta for the next ckSurf version here: https://github.com/jonitaikaponi/ckSurf/tree/1.18-Beta
This version has a completely different way on checking teleports, but it still needs testing.

If you know of any exploits, feel free to PM them to me and I'll get to fixing them.

**Comment by 4everGhost** [comment]
Bug for which I opened this issue was closed with this patch
