### ISSUE TITLE
Does this mess with core.cfg chat triggers?

### ISSUE THREAD

**Issue by PrinceDrew** [jonitaikaponi/ckSurf#30]
I have it reversed on my server so that "!" is the silentchattrigger and "/" is the public one but with this plugin everything is public.

**Comment by blackhawk74** [comment]
From what I can see, if you use the chat processing built into the plugin, it overrides all public/silent chat triggers, since it does not go through "normal" chat. An option to make "!" and/or "/" before chat commands not printed to chat would be ideal!

For now you can hide static chat commands using the /configs/ckSurf/hidden_chat_commands.txt file, however if you use a plugin, for example, such as !takeknife <name>, that will not be hidden.

**Comment by PrinceDrew** [comment]
I apologize blackhawk, I already fixed this issue a while back by talking to jonitaikaponi directly. He advised that you can add:
```javascript
if (sText[1] == '!' || sText[1] == '/'  )
	{
		g_bSayHook[client]=false;
		return Plugin_Handled;
	}
```
right after you declare and grab sText and this will block out **ANYTHING** that starts with "!" or "/".
