### ISSUE TITLE
Problems related to point system and plugin speed.

### ISSUE THREAD

**Issue by Seenko** [jonitaikaponi/ckSurf#33]
Hello,

I've added this beta version, updated all config files and translations, and edited those to fit the server format, the database I made a backup but left it untouched, everything is working fine, but people that are new on the server are *not* receiving points, even if they beat the WR for any map, and people who already played on the server are gaining too much points, also, the ranks points requirement got a little bit bigger, but with the scales for the ranks on the config the same as before.

The plugin is running in SQLite3, as I expected it's starting to get really slow, can you recommend a program that can convert the SQLite3 to MySQL? The one's I've tried parse half the DB, but then it messes up and gives me SQL Syntax Error...

Thanks for now and waiting for your reply,
Seenko.

**Comment by jonitaikaponi** [comment]
Hey,

Are you sure your mapcycle.txt has all the maps in it? The points have
indeed gone up for players who have played before, as you now gain more
points from bonuses (higher ranks earn more, rather than a flat 150 what
was before). Any error new logs in csgo/addons/sourcemod/logs?

I've never done an SQLite to MySQL conversion succesfully with a program,
but you can do it on a normal text editor pretty easily, if you know your
ways through basic regex.

2015-11-30 18:46 GMT+02:00 Seenko <notifications@github.com>:

**Comment by Seenko** [comment]
Hello,

I've searched through the logs and found nothing related to ckSurf itself, probably is the DB that's getting bigger and as a consequence slower, that players are not receiving points. This problem was reported by some users on the server and by someone on the forums (http://kinshi.co/problemas-tecnicos-no-servidor/problema-com-pontos | It's in portuguese). I'll take a look at that when I get home, in about 3 hours, just for curiosity if you want to test the problem yourself to see if it could really be the database, as I already said, no error logs related to ckSurf, the server IP is: csgo.kinshi.co
The server is allocated in south america, that's about 160+ latency to players that connect from North America.

Another question related to features in the plugin, I think I saw someone you said that surf modes/styles, like backwards/sideways was going to be developed, I wanted to know, how's the progress on that!

Thank you very much, and glhf with your time developing this awesome plugin!

Att,
Seenko_

**Comment by jonitaikaponi** [comment]
Hey,

Definately seems like something is really wrong with your database. There
was no zones in surf_eclipse and no SR on surf_classics even though some
people beat it.

There is currently no progress on different styles.

2015-11-30 19:01 GMT+02:00 Seenko <notifications@github.com>:

**Comment by Seenko** [comment]
I'll take a look on the entire database just to check it's integrity, while converting it to MySQL because, damn, SQLite3 is slow as hell (Kappa).

Thanks for your extremely quick support, like... WOW. I'm really amazed, never got support this quick on anything!

By the way, one last thing, is the line:
'''
g_BeamSprite = PrecacheModel("sprites/laserbeam.vmt");
'''
 Related to the actual zone beams sprite? I changed that line, recompiled, and pointed to the right file and it just stayed at the default sprite... I wanted to add my server name on it.

xoxo

**Comment by jonitaikaponi** [comment]
Yup thats it. Sprite is at ckSurf.sp and it is sent to the client at
surfzones.sp line 534 and 540. Try editing g_HaloSprite aswell, if nothing
else works.

No problemos

2015-11-30 20:00 GMT+02:00 Seenko <notifications@github.com>:

**Comment by Seenko** [comment]
Will do! I won't clode this issue just yet, when I get home I'll test everything out and then if everything is working fine, I'll leave my rating here.

For now I rate the support 8/8 m8!

**Comment by Seenko** [comment]
Hey there, I was trying to pin-point the reason why new players are not receiving points, and why some players are not receiving any points for when they complete a map for the first time...
That issue started to happen when the database was converted from sqlite to mysql, sucessfully with all the values, something gotta be wrong with the sql syntaxes in the plugin... I`m at work now and I can `t take a closer look at it, but it might be interesting to you, I`ll send the current database to you also.

Some random error that suggests that it might have other sql errors in the plugin: http://i.imgur.com/Tei2C7A.png

The database after being converted from sqlite to mysql:
https://drive.google.com/file/d/0B2G-1URPV6quNTJHdUhSWU5adlk/view?usp=sharing


You know more about your plugin so you might have a solution other than wiping the database, as it is quite large...

**Comment by jonitaikaponi** [comment]
Hey,

From looking at your database, I can see that it has lost the primary key
values. For an example in the ck_zones table mapname and zoneid should be
primary keys, but that information is not in your database. I don't think
that could cause the issue with points though. Do you happen to have your
database as an SQLite file from before you changed to 1.18b? I would want
to test that myself.

The SQL command that caused you the error is:

SELECT mapname, zoneid, zonetype, zonetypeid, pointa_x, pointa_y, pointa_z,
pointb_x, pointb_y, pointb_z, vis, team, zonegroup, zonename FROM ck_zones
WHERE mapname = '%s' ORDER BY zoneid ASC

where %s is the current map's name. There doesn't seem to be anything wrong
with the query, but it seems that for some reason your g_szMapName variable
was empty when that error happened, which is very strange.

The other error happens if you don't have a start zone in your map. My bad,
fixed it now.


2015-12-03 20:28 GMT+02:00 Seenko <notifications@github.com>:

**Comment by Seenko** [comment]
Okay, I used to have the stable version with SQLite on my main server, after that I saw that you've had opened a beta branch, and I quickly downloaded and installed on a local test server to see how it is (also using sqlite), I liked it so I installed the beta version on my main server while still using a SQLite database. Quickly that database was starting to get slow, even before updating, but I was just lazy to convert to MySQL, so about a day after installing the beta version on my main server, I converted the databse to MySQL and fired it up, I got my rank, so I suppose that it worked fine, until some users stated that they were not receiving points (new users, probably first joined after the db/plugin update, I can't be so sure), and one user was losing points whenever he finished a map, some others were receiving small amount of points, and one user (He's top #1) received 5k points by just finishing a map, not even top 10 on the map.

**Comment by jonitaikaponi** [comment]
That could all be because of how the ranking system works though, except
for the new players not gaining points.

The #1 guy probably has a lot of high ranks in bonuses, which in this
newest update gives more points than before, so when he finished that map
and his points got recalculated, he gained all those extra points from the
bonuses that he didn't have before. Some people might be losing points,
because they had finished a lot of bonuses, but their ranks were really low
in them so now they lost points in the new system. But even if they would
lose points from dropping points in the bonuses, they wouldn't always be
losing points, only when their rank had dropped in other maps.

Check !help2 for more info on the point system.

(Old system gave a flat 150 points when finishing a bonus, now higher rank
in the bonus gives more points.)

2015-12-03 21:06 GMT+02:00 Seenko <notifications@github.com>:

**Comment by Seenko** [comment]
You can take a look on people stats here http://top.kinshi.co/ (main reason that I converted to MySQL).
That makes sense, but why some people are not receiving points, that's the main issue people are complaining about...

Could you tell me which values are the primary keys for those tables, "what if", right?

**Comment by jonitaikaponi** [comment]
spawnlocations: mapname, zonegroup
playerflags: steamid
challenges: steamid,steamid2,date
zones: mapname, zoneid
maptier: mapname
bonus: steamid, mapname, zonegroup
checkpoint: steamid, mapname, zonegroup
latest records: steamid,map,date
playeroptions: steamid
playerrank: steamid
playertimes: steamid,mapname
playertemp: steamid,mapname

2015-12-03 21:20 GMT+02:00 Seenko <notifications@github.com>:

**Comment by LeeStrong7** [comment]
Joni - Can't find "playerflags" anywhere. Having same issue as above also.

**Comment by jonitaikaponi** [comment]
Ah sorry, it is playertitles.
4.12.2015 23.08 "LeeStrong7" <notifications@github.com> kirjoitti:

**Comment by Seenko** [comment]
Joni, a user is telling that when he finished a map he does not receive points, that we already knew, but he said that when he types !rank he has no time set for his run, I suppose a permission error or maybe the plugin sending a misformatted sql query for mysql?

**Comment by jonitaikaponi** [comment]
If you have an SQL error in cksuf, it will show in
sourcemods/logs/errors_xxx.log. please post those files if they include
ckSurf.

The other reason that I've been suspecting for causing this is that you
didn't give your server enough time to make all the changes correctly in
the database, but that doesn't seem to be the issue on a brief overlook.

I'd really like to test this on a large database.
5.12.2015 1.29 "Seenko" <notifications@github.com> kirjoitti:

**Comment by Seenko** [comment]
The only SQL Error that I have is on db_checkAndFixZoneIdsCallback, about doesn't have enough time to make all the changes correctly in the database, maybe it could be, new players are at the bottom of the database, so they coould have that problem, where could I change that in PHPMyAdmin?

**Comment by LeeStrong7** [comment]
Folks - I can fix the points on MY servers by;
Completing Bonus 1 on ANY map will allow the player to gain points on any other (including current) map, refresh profile etc.

Without bonus 1 completion, they can't get ANY points at all.

**Comment by Seenko** [comment]
I think I've heard a using talking about that, but it was a couple minutes after we recalculated player points so we thought it was due to that, when I get home I'll test on another account if I can replicate, but I'm pretty sure that's the case tho....

**Comment by Seenko** [comment]
Well, I could replicate the problem and your work-around, but I guess I found a definite fix.

The Problem: You used to have a SQLite3 database, found a way to convert it to MySQL and it kinda works, but new players do not receive points unless they finish a bonus first.

How to Fix:
1. Login to your MySQL Database and make a backup of the database, but just the data insertion queries, do not export with table creation queries.

2. Make sure ckSurf is already configured to use the new MySQL Database and start the server. Now the plugin will create all the new tables on the clean MySQL Database.

3. Login back to you new MySQL Database, make sure all the tables are created with NO DATA, and continue to import your previously backed up archive. Make sure to IGNORE DUPLICATES (It's been a while and all maps were played, no problems about that duplicated data), otherwise the data will not be imported.

5. You're done! Now your server should work fine.

LeeStrong7, try to do the same and see if it works for you!

**Comment by jonitaikaponi** [comment]
Hey, this was already fixed yesterday.
11.12.2015 7.52 ip. "Seenko" <notifications@github.com> kirjoitti:
