### ISSUE TITLE
The plugin doesn't give points when finishing maps

### ISSUE THREAD

**Issue by Dirazi** [jonitaikaponi/ckSurf#45]
Users on my server have reported when they finish a map/get map record they receive no points. Saw one of my admins do it they indeed got no points.

**Comment by jonitaikaponi** [comment]
This is because you connected to your server too quickly after installing
1.18. That interrupted the plugin making changes to your database.

You now have two choices
1. Revert back to your backup of the 1.17 database, launch the server with
the 1.18 and properly follow the update instructions.
2. You can try running the commands in the Optional Files/1.17-1.18.sql on
your database to fix it. This can though cause issues with your zones, and
then you'd have to run !insertmapzones again.
19.12.2015 10.43 ap. "Dirazi" <notifications@github.com> kirjoitti:
