### ISSUE TITLE
Question: 1 DB on 2 servers?

### ISSUE THREAD

**Issue by zAfLu** [jonitaikaponi/ckSurf#58]
Hi,

do you know if it's possible to run ckSurf on a single Database with two csgo servers?
I try to build one single ranking system to share the ranking on diffrent surf servers,

**Comment by jonitaikaponi** [comment]
Yes,

You just have to have the same mapcycle.txt and the same maps in the maps
folder on both server and it works fine.

2016-01-08 13:13 GMT+02:00 zAfLu <notifications@github.com>:

**Comment by zAfLu** [comment]
All servers got the same map folder but not the same mapcycle because of different tiers.

Any ideas how to make that possible?

**Comment by jonitaikaponi** [comment]
Make your mapchooser use another file.

2016-01-08 13:23 GMT+02:00 zAfLu <notifications@github.com>:

**Comment by marcowmadeira** [comment]
What about adding a cvar for the total maps instead? If we set it to 0 would use current method

**Comment by jonitaikaponi** [comment]
The mapcycle check does more than count the maps, it also checks that the
times in your database are in maps that are in your mapcycle, so it knows
to give points or not.

2016-01-08 13:58 GMT+02:00 Marco Madeira <notifications@github.com>:

**Comment by zAfLu** [comment]
What about:

Adding a CVAR like ck_multiserver_ranking 1/0 which allows to merge different mapcycles to one ranking cycle?

**Comment by 4everGhost** [comment]
Hey,

I did run such a configuration for a few days and it worked fine. One Server was a live system with a static mapcycle and the other one was a testing server to test new maps.

What I noticed was that when I finished a map on the testing server and did come back to my live system, I had lost a lot of points but got them back after I set a new PB on the livesystem.

I dont know the exact configuration anymore but the new map records on the testing server was out of the mapcycle of both servers. That might be the reason for this but you should check it before making it live.

**Comment by jonitaikaponi** [comment]
`4everGhost`
Yeah, it will show you as losing a lot of points, because it calculated your points on the test server and it then used the mapcycle and maps on that server to calculate the points. When you went onto your live server and finished a map, it recalculated your points with the real mapcycle and maps so it showed your points correctly again. Thats why you have to have the same mapcycle and maps.

`zAfLu`
I'd recreate the g_MapList with a new method. I pushed an idea on it, but it's not tested. 
So set ck_multi_server_mapcycle to 1, and it should read your mapcycle from configs/ckSurf/multi_server_mapcycle.txt. This also ignores maps in the /maps folder, so you don't have to have the .bsp files in.

See if this works.

**Comment by zAfLu** [comment]
Ok thanks.

I will give you feedback after testing. :) (Maybe today or tomorrow, so much stuff todo T_T)
